- name: bug
  color: 'd73a4a'
  description: Something is not working

- name: enhancement
  color: 'a2eeef'
  description: New feature or request

- name: dependencies
  color: '0366d6'
  description: Dependency update or maintenance
